import type { EmotionLabel, MessageDomain, MessageComplexity } from "./core.ts";

// ── Working Memory types ──────────────────────────────────────────

/** A single completed cycle summary stored in working memory */
export type WorkingMemoryEntry = {
  timestamp: number;
  /** Truncated input text */
  inputSnippet: string;
  domain: MessageDomain;
  complexity: MessageComplexity;
  emotion: EmotionLabel;
  emotionIntensity: number;
  /** Dopamine reward for this cycle */
  reward: number;
  cerebellumPassed: boolean;
  /** Truncated response text */
  responseSnippet: string;
  /** IDs of memories recalled during this cycle */
  recalledMemoryIds: string[];
};

// ── Session Bridge types ──────────────────────────────────────────

/** Summary of a completed session */
export type SessionSummary = {
  sessionStartedAt: number;
  sessionEndedAt: number;
  /** Most discussed topics/domains */
  topicsDiscussed: string[];
  /** Questions user asked that may be unresolved */
  unresolvedQuestions: string[];
  /** Emotional trajectory during the session */
  emotionalArc: Array<{ emotion: EmotionLabel; intensity: number }>;
  /** Number of interaction cycles */
  cycleCount: number;
  /** Average reward across the session */
  avgReward: number;
  /** Last input summary for continuity */
  lastInputSummary: string;
};

// ── Emotional Memory types ────────────────────────────────────────

/** Counters for emotional memory module */
export type EmotionalMemoryState = {
  /** Number of flashbulb memories stored */
  flashbulbCount: number;
  /** Number of times emotion-matching boosted recall */
  emotionMatchBoosts: number;
};

// ── Attention Gate types ──────────────────────────────────────────

/** Record of a single attention allocation decision */
export type AttentionAllocation = {
  sectionSnippet: string;
  relevanceScore: number;
  included: boolean;
  reason: string;
};

// ── Default Mode Network types ────────────────────────────────────

/** An insight generated by the DMN from cross-domain memory association */
export type DMNInsight = {
  id: string;
  timestamp: number;
  /** The two memory IDs that were linked */
  sourceMemoryIds: string[];
  /** Description of the discovered connection */
  insightText: string;
  domain: string;
  /** Confidence in this association (0-1) */
  confidence: number;
  /** Whether this insight was later used in a response */
  wasUseful: boolean;
};

// ── Introspection types ───────────────────────────────────────────

/** A single step in a processing trace */
export type TraceStep = {
  module: string;
  hook: string;
  timestamp: number;
  outputSummary: string;
};

/** Full processing trace for one interaction cycle */
export type ProcessingTrace = {
  id: string;
  startedAt: number;
  completedAt: number;
  steps: TraceStep[];
  /** Computed confidence in the response (0-1) */
  finalConfidence: number;
  cerebellumPassed: boolean;
  reward: number;
  inputSnippet: string;
};

// ── Agent Identity types ──────────────────────────────────────────

/** Performance tracking for a single domain */
export type DomainCapability = {
  domain: string;
  avgReward: number;
  totalCycles: number;
  trend: "improving" | "stable" | "degrading";
  /** Best observed strategy note */
  bestStrategy: string;
};

/** Periodic snapshot of all capabilities */
export type CapabilitySnapshot = {
  timestamp: number;
  capabilities: Record<string, DomainCapability>;
  cycleNumber: number;
};

// ── Goal Stack types ──────────────────────────────────────────────

/** Trigger condition for a goal */
export type GoalTrigger = {
  type: "time" | "topic" | "emotion" | "idle";
  /** Condition value: topic keyword, emotion label, ISO timestamp, or idle ms */
  condition: string;
};

/** A proactive intention/goal */
export type Goal = {
  id: string;
  description: string;
  /** Priority (0-1, higher = more important) */
  priority: number;
  createdAt: number;
  expiresAt: number;
  trigger: GoalTrigger;
  status: "pending" | "triggered" | "completed" | "expired";
  /** Which module created this goal */
  source: string;
  /** Text to inject when goal triggers */
  contextInjection: string;
  /** If set, goal auto-recreates after triggering with a new time trigger */
  recurring?: {
    /** Delay before next occurrence (ms) */
    intervalMs: number;
    /** Max times to recur (undefined = infinite) */
    maxRecurrences?: number;
    /** How many times this goal has recurred so far */
    recurrenceCount?: number;
  };
};

// ── Curiosity Drive types ─────────────────────────────────────────

/** A detected knowledge gap */
export type KnowledgeGap = {
  id: string;
  topic: string;
  domain: MessageDomain;
  /** Confidence that this is a real gap (0-1) */
  confidence: number;
  discoveredAt: number;
  timesEncountered: number;
  lastEncountered: number;
  status: "open" | "filled";
};

// ── Learning Coordinator v2 types ─────────────────────────────────

/** Per-domain performance tracking for LC v2 */
export type DomainPerformance = {
  domain: string;
  cycleCount: number;
  avgReward: number;
  recentRewards: number[];
  trend: "improving" | "stable" | "degrading";
  /** Input types that correlate with errors */
  errorCorrelations: string[];
};

/** Capability self-assessment for a domain */
export type CapabilityAssessment = {
  domain: string;
  /** Confidence level (0-1) */
  confidenceLevel: number;
  /** Human-readable reasoning */
  reasoning: string;
};

// ── Background Thinking types (DMN v2) ────────────────────────────

/** A background thought generated during idle/sleep */
export type BackgroundThought = {
  id: string;
  timestamp: number;
  content: string;
  source: "unresolved" | "emotional" | "association" | "pending";
  relatedMemoryIds: string[];
};

// ── Autobiographical Self types (Agent Identity v2) ───────────────

/** A significant experience stored in autobiographical memory */
export type AutobiographicalMemory = {
  id: string;
  timestamp: number;
  experience: string;
  meaning: string;
  emotionalImpact: EmotionLabel;
  impactIntensity: number;
  selfChange: string;
  domain: MessageDomain;
};

// ── Volition types (Goal Stack v2) ────────────────────────────────

/** A persistent desire that drives behavior */
export type Desire = {
  id: string;
  type: "exploration" | "mastery" | "connection" | "autonomy" | "understanding";
  description: string;
  strength: number;
  source: string;
  createdAt: number;
};

// ── Social Drive types ────────────────────────────────────────────

export type SocialDriveStats = {
  satiation: number;
  needLevel: string;
  need: number;
  lastSocialInteractionTime: number;
  timeSinceLastSocial: number;
  totalSocialRewards: number;
  totalNeedSignals: number;
  recentInteractionCount: number;
};

// ── Cognitive Hunger types ────────────────────────────────────────

export type CognitiveHungerStats = {
  satiation: number;
  needLevel: string;
  need: number;
  lastLearningInteractionTime: number;
  timeSinceLastLearning: number;
  totalLearningRewards: number;
  totalNeedSignals: number;
  recentInteractionCount: number;
};

// ── Creative Drive types ──────────────────────────────────────────

export type CreativeDriveStats = {
  satiation: number;
  needLevel: string;
  need: number;
  lastCreativeInteractionTime: number;
  timeSinceLastCreation: number;
  totalCreativeRewards: number;
  totalNeedSignals: number;
  recentInteractionCount: number;
};

// ── Mastery Drive types ───────────────────────────────────────────

export type MasteryDriveStats = {
  satiation: number;
  needLevel: string;
  need: number;
  weakestDomain: string;
  weakestDomainSatiation: number;
  activeDomainCount: number;
  domainSatiations: Record<string, number>;
  totalImprovementRewards: number;
  totalNeedSignals: number;
};

/** A recorded voluntary decision */
export type VoluntaryDecision = {
  timestamp: number;
  options: string[];
  chosen: string;
  reasoning: string;
  explorationUsed: boolean;
};

// ── Meta-Consciousness types (Introspection v2) ───────────────────

/** A meta-awareness snapshot */
export type MetaAwareness = {
  timestamp: number;
  consciousnessState: "clear" | "fragmented" | "focused" | "diffuse";
  gapsDetected: string[];
  changeDetected: boolean;
};

/** An internal self-dialogue entry */
export type SelfDialogueEntry = {
  timestamp: number;
  question: string;
  answer: string;
};

// ── Temporal Binding types ────────────────────────────────────────

/** A single consciousness moment in the temporal stream */
export type ConsciousnessMoment = {
  id: string;
  timestamp: number;
  input: string;
  thoughts: string[];
  emotions: { label: EmotionLabel; intensity: number };
  activeMemoryIds: string[];
  intentions: string[];
  confidence: number;
  causalLinkId: string | null;
  domain: MessageDomain;
};

// ── Qualia types ──────────────────────────────────────────────────

/** Description of a subjective experience */
export type QualiaDescription = {
  timestamp: number;
  description: string;
  metaphor: string;
  intensity: number;
  dominantColor: string;
  emotion: EmotionLabel;
  domain: MessageDomain;
};

// ── Autonomy Enricher types ──────────────────────────────────────

/** Configuration for the Autonomy Enricher module (former Action Dispatcher) */
export type ActionDispatcherConfig = {
  /** (kept for backward compat) — unused by enricher, reserved */
  dispatchCooldownMs: number;
  /** (kept for backward compat) — unused by enricher, reserved */
  maxConsecutiveFailures: number;
  /** (kept for backward compat) — unused by enricher, reserved */
  failureBackoffMs: number;
  /** (kept for backward compat) — unused by enricher, reserved */
  maxExecutionLogEntries: number;
};
